In [9]:
import tensorflow as tf
import keras
from keras import layers

In [2]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"), # After this step the matrix is 3x2
        layers.Dense(3, activation="relu", name="layer2"), # After this step the matrix is 3x3 (3x2 * 2x3)
        layers.Dense(4, name="layer3"), # After this step the matrix is 3x4 (3x3 * 3x4)
    ]
)

x = tf.ones((3, 3))
y = model(x)
#print(y.numpy())
for layer in model.layers:
    print(layer.name)
    weights, biases = layer.get_weights()
    print("Weights:", weights)
    print("Biases:", biases)
    print("------------")


layer1
Weights: [[-0.45064896 -0.80156666]
 [-0.9084189   0.54442704]
 [-0.5078331   0.3257606 ]]
Biases: [0. 0.]
------------
layer2
Weights: [[-0.91771674 -0.9504779   0.01051986]
 [-0.8204543   0.7310475  -0.9209618 ]]
Biases: [0. 0. 0.]
------------
layer3
Weights: [[-0.68157256 -0.4408112   0.5629802  -0.58195275]
 [ 0.6795447   0.1905365  -0.13701916  0.86082447]
 [-0.50578296 -0.45363665  0.41097116  0.46413958]]
Biases: [0. 0. 0. 0.]
------------


In [3]:
# List all the layers in the model.
model.layers

In [4]:
# Generally, all layers in Keras need to know the shape of their inputs 
# in order to be able to create their weights. So when you create a layer like this, 
# initially, it has no weights:
layer = layers.Dense(2)
print(layer.weights)  # Empty


[]


In [5]:
x = tf.ones((3, 3))
y = layer(x)
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(3, 2) dtype=float32, numpy=
 array([[ 0.58545136, -0.8404145 ],
        [-0.6420465 ,  0.95417356],
        [ 0.5112399 ,  1.0028882 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [6]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)  # No weights at this stage!

# At this point, you can't do this:
# model.weights

# You also can't do this:
# model.summary()
    

# Call the model on a test input
x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))  # 6

Number of weights after calling the model: 6


In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (1, 2)                    10        
                                                                 
 dense_2 (Dense)             (1, 3)                    9         
                                                                 
 dense_3 (Dense)             (1, 4)                    16        
                                                                 
Total params: 35 (140.00 Byte)
Trainable params: 35 (140.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
# More complex model
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# Can you guess what the current output shape is at this point? Probably not.
# Let's just print it:
model.summary()

# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

# And now?
model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 123, 123, 32)      2432      
                                                                 
 conv2d_1 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2  (None, 40, 40, 32)        0         
 D)                                                              
                                                                 
Total params: 11680 (45.62 KB)
Trainable params: 11680 (45.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 123, 123, 32)      2432   