In [47]:
import numpy as np
import tensorflow as tf

In [48]:
x: tf.Tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(x)
x: str = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-1.16991   ]
 [-0.5553992 ]
 [-0.21918781]], shape=(3, 1), dtype=float32)


In [58]:
x = np.ones(shape=(2,2))
print(x)
x[0,0] = 0
x[0,1] = 123
print(x)
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
v.assign(tf.ones(shape=(3,1)))
print(v)
v.assign_add(tf.ones(shape=(3,1)))
print(v)

[[1. 1.]
 [1. 1.]]
[[  0. 123.]
 [  1.   1.]]
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [2.],
       [2.]], dtype=float32)>


In [80]:
input_var = tf.Variable(initial_value=3.) # Shape 0
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
# Tính đạo hàm riêng của result theo input_var
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [89]:
# Xét 1 ví dụ hàm có nhiều biến đầu vào
input_vars = tf.Variable(initial_value=[1., 2., 3., 4.]) # Shape 1
with tf.GradientTape() as tape:
    # Tính giá trị hàm số
    result = tf.abs(input_vars)
# Tính đạo hàm riêng của result theo input_vars
gradients = tape.gradient(result, input_vars)
print(gradients)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)


In [103]:
# Tính gradient của hàm 3x + 2y
x = tf.Variable(initial_value=3.)
y = tf.Variable(initial_value=2.)
with tf.GradientTape() as tape:
    result = 11*x*x + 12*y
gradients = tape.gradient(result, [x, y])
print("Gradient with respect to x:", gradients[0].numpy())
print("Gradient with respect to y:", gradients[1].numpy())

Gradient with respect to x: 66.0
Gradient with respect to y: 12.0


In [100]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [106]:
# Tính đạo hàm bậc 2 của hàm số y = x^2 + 2x + 1
x = tf.Variable(initial_value=123.)
with tf.GradientTape() as tape_1:
    with tf.GradientTape() as tape_2:
        y = x * x + 2 * x + 1
    # Tính đạo hàm bậc nhất của y theo x
    dy_dx = tape_2.gradient(y, x)
# Tính đạo hàm bậc 2 của y theo x
d2y_dx2 = tape_1.gradient(dy_dx, x)
print(d2y_dx2)

tf.Tensor(2.0, shape=(), dtype=float32)
