In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a.shape)  # (3,) mean 1D array with 3 elements
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print(b.shape)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
print(c.shape)


In [4]:
print(np.zeros((3, 4)))
print(np.ones((2, 3, 4), dtype=np.int16))
d = np.arange(10, 25, 5)  #Create an array of evenly spaced values (step value)
np.linspace(0, 2, 9)  #Create an array of evenly spaced values (number of samples)
e = np.full((2, 2), 7)  #Create a constant array
f = np.eye(2)  #Create a 2X2 identity matrix
print(f)
np.random.random((2, 2))  #Create an array with random values


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1. 0.]
 [0. 1.]]


array([[0.85262595, 0.18357908],
       [0.80270695, 0.07204888]])

In [5]:
print(np.empty((3, 2)))  #Create an empty array

[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [6]:
# reshape the array
print(np.arange(10))
print(np.arange(10).reshape(2, 5))
print(np.arange(10).reshape(5, 2))
print(np.arange(10).reshape(2, -1))  # -1 means "whatever is needed"
print(np.arange(10).reshape(-1, 5))  # -1 means "whatever is needed"
print(np.arange(10).reshape(2, 1, -1))  # -1 means "whatever is needed"
print(np.arange(10).reshape(10,1))
 # flatten the array
print(np.arange(10).flatten())
print(np.arange(10).reshape(1,-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]


In [7]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
i = np.transpose(b)
print(i)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
